ruby '3.1.3'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.6', '>= 4.6.0'
gem 'middleman-syntax', '~> 3.5', '>= 3.5.0'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-sprockets', '~> 4.1'
gem 'rouge', '~> 3.21'
gem 'redcarpet', '~> 3.6.0'
gem 'nokogiri', '~> 1.18.9'
gem 'sprockets', '~> 4.0', '>= 4.0.0'
gem 'sass'
gem 'webrick'
